### ISSUE TITLE
Test against Python 3.12 once dbt-core supports it

### ISSUE THREAD

**Issue by binste** [binste/dbt-ibis#47]
Waiting for https://github.com/dbt-labs/dbt-core/issues/9007. 

Can then `git revert 7a8c9ff1a64a7e91304d46bec4a88e7d157887de`

**Comment by dbeatty10** [comment]
@binste Support for Python 3.12 was just recently released in [dbt-core 1.7.9](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/CHANGELOG.md#dbt-core-179---february-28-2024).

**Comment by binste** [comment]
Thank you very much for letting me know! :)
