### ISSUE TITLE
Docs: © Copyright 2022

### ISSUE THREAD

**Issue by Riezebos** [binste/dbt-ibis#48]
Hi, I was reading about dbt-ibis and it looks really great! When I saw "© Copyright 2022" at the bottom I was a bit worried that the project was stale/outdated. Then I saw the activity on Github and everything and my worries went away again :)

As far as I can tell the 2022 is not hardcoded in the docs source code.

Others might have the same worries or even dismiss the project if they are just having a cursory look, maybe it would be good to update this to 2024?

**Comment by binste** [comment]
Thank you @Riezebos for letting me know and for the feedback, much appreciated! :) I wasn't aware of that. I also don't know what year to rally put there. According to [this page](https://www.copyrightlaws.com/copyright-symbol-notice-year/#:~:text=The%20general%20rule%20is%20that,posting%20content%20on%20your%20blog.) and [this SO answer](https://stackoverflow.com/a/2391555) it should be the year of the first publication so I'm changing it to 2023.

I'm actively maintaining this project and will further develop it based on user needs. I'd also love to better integrate this with dbt, see [here](https://binste.github.io/dbt-ibis/advanced.html#potential-closer-integration-with-dbt). If you have any ideas on how to improve it, let me know!

**Comment by Riezebos** [comment]
Ah you're right. TIL how copyright actually works...
