### ISSUE TITLE
Feature: Use dbt python models instead of compiling to sql

### ISSUE THREAD

**Issue by feluelle** [binste/dbt-ibis#58]
[dbt supports python models](https://docs.getdbt.com/docs/build/python-models) which means we don't need to compile ourselves. We can just the python api.

**Comment by binste** [comment]
Could you elaborate on how you'd see this work? In my understanding, there are the following issues:

* In Python models, you get dataframes which, in my understanding, are either pandas dataframes or are platform dependent. It's unclear to me how we can use Ibis on top of those
* It requires that your Python code is run in a cloud data warehouse and often, that data is moved into a Python process which can be slower than leveraging the power of modern SQL engines.
* Following from the above points, this approach only works for the few platforms which support Python models. The current approach works for many more

**Comment by feluelle** [comment]
You are right, I missed that it only supports three cloud data warehouses. I re-read your blog post and it makes sense to compile from Python to SQL as part of `dbt-ibis`.
